### ISSUE TITLE
Add file-based library persistence

### ISSUE THREAD

**Issue by geoah** [42minutes/go-42minutes#19]
Currently we have user library using rethinkdb which is a bit limiting as it requires users to have rethink installed or user docker.

We could really use some form of file-based nosql library that will allow the users to not have to install any external dbs. eg, tiedot

**Comment by alexmreis** [comment]
SQLite?

**Comment by geoah** [comment]
Hm. I was about to say that the main issue of using SQLite is the structure and query complexity.
But...

We only need persistence for the user library for which we don't actually store the whole structure any more.

@alexmreis I think you are on to something.

## Tables

### Shows
- `id`
- `title`

### Seasons
- `show_id`
- `number`

### Episodes
- `show_id`
- `season`
- `episode`
- `title`

### Files
- `show_id`
- `season`
- `episode`
- `name`
- `path`
- `infohash`
- `resolution`
- `source`
- `video_codec`
- `audio_codec`
- `release_group`
- `crc32`
- `status`
- `retry_time`

## Queries

Some functionality of the user library might require additional queries but that should be an issue as scaling in a single-user client isn't really a concern.

@superdecimal should we switch to a relational db maybe?

**Comment by superdecimal** [comment]
@geoah What would be the advantages besides me not being able to find a decent embeddable nosql db?

**Comment by geoah** [comment]
@superdecimal apparently there is no such thing in golang.
